//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

public class Main
{
  public static void main (String[]args)
  {
    int sum = 0;
    int num1 = 1;
    int num2 = 2;
    int nextfib = num1+num2;
    sum = 2;

    while(nextfib < 4000000){
        
        nextfib = num1+num2;
        num1 = num2;
        if(nextfib%2 == 0)
            sum += nextfib;
        num2 = nextfib;
    }
    
    System.out.println(sum);
    
  }
}
